#!/bin/sh
# $FreeBSD$

# PROVIDE: sysadm-rest
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable sysadm:
# sysadmr_rest_enable (bool):	Set to "NO" by default.
#				Set it to "YES" to enable sysadm

. /etc/rc.subr

name="sysadm_rest"
rcvar=sysadm_rest_enable

start_cmd="sysadm_rest_start"
stop_cmd="sysadm_rest_stop"
flags="-rest"

[ -z "$sysadm_rest_enable" ] && sysadm_rest_enable="NO"

load_rc_config $name

ssl_keygen()
{
  if [ ! -d "/usr/local/etc/sysadm" ] ; then
    mkdir -p /usr/local/etc/sysadm
  fi
  openssl req -x509 -nodes -newkey rsa:2048 \
	-keyout /usr/local/etc/sysadm/restserver.key \
	-out /usr/local/etc/sysadm/restserver.crt -days 1024 \
	-subj "/C=US/ST=MY/L=NULL/O=SysAdm/OU=SysAdm/CN=SysAdm/emailAddress=none@example.org" 2>/dev/null
}

sysadm_rest_stop()
{
  if [ -e "/var/run/sysadm-rest.pid" ] ; then
    pkill -9 -F /var/run/sysadm-rest-daemon.pid >/dev/null 2>/dev/null
    pkill -9 -F /var/run/sysadm-rest.pid >/dev/null 2>/dev/null
  fi
}

sysadm_rest_start()
{
  export PATH="${PATH}:/usr/local/bin:/usr/local/sbin"
  sysadm_rest_stop
  ssl_keygen
  echo "Starting sysadm (REST)..."
  command="/usr/local/bin/sysadm-server"
  daemon -r -P /var/run/sysadm-rest-daemon.pid -p /var/run/sysadm-rest.pid $command $flags >/dev/null 2>/dev/null
  chmod 744 /var/run/sysadm-rest.pid >/dev/null 2>/dev/null
}

run_rc_command "$1"
