#!/bin/sh
# $FreeBSD$

# PROVIDE: sysadm-restserver
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable sysadm:
# sysadmr_restserver_enable (bool):		Set to "NO" by default.
#				Set it to "YES" to enable sysadm

. /etc/rc.subr

name="sysadm_restserver"
rcvar=sysadm_restserver_enable

command="/usr/local/bin/sysadm-server"
start_cmd="sysadm_start"
stop_cmd="sysadm_stop"
flags=""

[ -z "$sysadm_restserver_enable" ] && sysadm_restserver_enable="NO"

load_rc_config $name

sysadm_stop()
{
  if [ -e "/var/run/sysadm-rest.pid" ] ; then
    pkill -9 -F /var/run/sysadm-rest.pid
  fi
}

sysadm_start()
{
  export PATH="${PATH}:/usr/local/bin:/usr/local/sbin"
  sysadm_stop
  echo "Starting sysadm (REST)..."
  daemon -p /var/run/sysadm-rest.pid $command $flags >/dev/null 2>/dev/null
}

run_rc_command "$1"
