#!/bin/sh
# $FreeBSD$

# PROVIDE: sysadm_websocket
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable sysadm:
# sysadm_websocket_enable (bool):		Set to "NO" by default.
#						Set it to "YES" to enable sysadm

. /etc/rc.subr

name="sysadm_websocket"
rcvar=sysadm_websocket_enable

command="/usr/local/bin/sysadm-server"
start_cmd="sysadm_start"
stop_cmd="sysadm_stop"
flags="-ws"

[ -z "$sysadm_websocket_enable" ] && sysadm_websocket_enable="NO"

load_rc_config $name

sysadm_stop()
{
  if [ -e "/var/run/sysadm-websocket.pid" ] ; then
    pkill -9 -F /var/run/sysadm-websocket.pid
  fi
}

sysadm_start()
{
  export PATH="${PATH}:/usr/local/bin:/usr/local/sbin"
  sysadm_stop
  echo "Starting sysadm (WebSocket)..."
  daemon -p /var/run/sysadm-websocket.pid $command $flags >/dev/null 2>/dev/null
}

run_rc_command "$1"
